apiVersion: v2
name: kubectyl
description: Put your servers on autopilot with Kubernetes implementation and get rid of Pterodactyl nodes.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: mariadb
  version: "11.3.0"
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: "17.3.11"
  repository: https://charts.bitnami.com/bitnami
