apiVersion: v1
kind: Service
metadata:
  name: {{ include "panel.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: panel
  {{- with .Values.panel.serviceAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
  - name: web
    port: 443
  selector:
    app: panel
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuber.fullname" . }}
  labels:
    app: kuber
  {{- with .Values.kuber.serviceAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 443
  selector:
    app: kuber
